customCommands:
  - key: "<c-a>"
    description: "Generate AI Commit"
    context: "files"
    outputTitle: "\U0001F916 Commit Message Generated"
    loadingText: "\U0001F916 AI is thinking..."
    command: 'sh -c "python $HOME/meza-profile-zsh/bin/ai_commit_generator"'
    output: popup
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
os:
  editPreset: "zed"
